modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/GlobalXP/blob/neoforge/1.20.6/LICENSE"

[[mods]]
	modId="globalxp"
	version="${file.jarVersion}"
	displayName="Global XP"
	description='''Adds a fast way to store XP and share it with your friends!'''
	issueTrackerURL="https://github.com/bl4ckscor3/GlobalXP/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/global-xp"
	authors="bl4ckscor3"

[[mixins]]
    config="globalxp.mixins.json"

[[dependencies.globalxp]]
    modId="neoforge"
    type="required"
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.globalxp]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"